version: '2'
services:
    logstash:
        image: docker.elastic.co/logstash/logstash:5.6.10
        restart: unless-stopped
        container_name: logstash
        volumes:
            - ./config/:/usr/share/logstash/config/
